default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: MtDbPass
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mv_api_dev

test:
  <<: *default
  database: mv_api_test

production:
  <<: *default
  database: movie_api_production
  username: movie_api
  password: <%= ENV['MOVIE_API_DATABASE_PASSWORD'] %>
